@startuml
actor User
User -> MobileApp: (1) Open mobile app then click xxx service
MobileApp -> AuthenticationService : (1.1) Request access_token \nwith [xxx,profile,payment] scope
AuthenticationService --> AuthenticationService: (1.2) Create access_token \nwith [xxx,profile,payment] scope
AuthenticationService --> MobileApp : (1.3) return access_token \nwith [xxx,profile,payment] scope

MobileApp -> WebView : (1.4) Open WebView with access_token
WebView -> ProfileService: (1.5) Get profile from resource server
ProfileService --> ProfileService : (1.6) Check access_token has profile scope
ProfileService --> WebView : (1.7) return user profile

WebView --> User : Render xxx service with user profile

User -> WebView: (2) User browse xxx WebView
WebView -> YourOwnService: (2.1) Do your own business
YourOwnService --> YourOwnService: (2.2) Check access_token has xxx scope \nand do processing your service
YourOwnService --> WebView: (2.3) Return your business data
WebView --> User : Render your business data

User -> WebView : (3) User click payment
WebView -> PaymentService: (3.1) Call payment with access_token
PaymentService --> PaymentService: (3.2)  Check access_token \nhas payment scope and do payment
PaymentService --> WebView: (3.3) Return payment txn status
WebView --> User: Render payment status to user

@enduml